version: '2'

services:
  zoo:
    image: zookeeper:3.4.9
    hostname: zoo
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo:2888:3888

  kafka:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_JMX_PORT: 9991
    depends_on:
      - zoo

  # Begin kafka client section
  kafka-client:
    image: confluentinc/cp-enterprise-kafka:4.0.0
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b kafka:9092 1 60 && \
                       sleep 5 && \
                       kafka-topics --zookeeper zoo:2181 --topic bids --create --replication-factor 1 --partitions 1 && \
                       exit'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
  # End kafka-client section

#  # Begin Schema Registry section
#  schemaregistry:
#    image: confluentinc/cp-schema-registry:4.0.0
#    #restart: always
#    depends_on:
#      - zoo
#    environment:
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
#      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
#      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8082"
#    ports:
#      - 8082:8082
#  # End Schema Registry section
#
#  # Begin ksql section
#  ksql-cli:
#    image: "confluentinc/ksql-cli:0.5"
#    hostname: ksql-cli
#    depends_on:
#      - kafka
#      - schemaregistry
#    ports:
#      - "9098:9098"
#    volumes:
#      - ./ksql.properties:/tmp/ksql.properties
#    command: "perl -e 'while(1){ sleep 99999 }'"
#    environment:
#      KSQL_CONFIG_DIR: "/etc/ksql"
#      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
#      STREAMS_BOOTSTRAP_SERVERS: kafka:9092
#      STREAMS_SCHEMA_REGISTRY_HOST: schemaregistry
#      STREAMS_SCHEMA_REGISTRY_PORT: 8082
#      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#  # End ksql section